// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRKNCCCZXt-cPFX6nvSGQpTI-D3LbxTR8',
    appId: '1:801172071927:web:10fd1577ec678cd9bdfaf2',
    messagingSenderId: '801172071927',
    projectId: 'dw-7-job-timer-1cb68',
    authDomain: 'dw-7-job-timer-1cb68.firebaseapp.com',
    storageBucket: 'dw-7-job-timer-1cb68.appspot.com',
    measurementId: 'G-KHXE0M5CHL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi_8j6SqOJPnNfEXzvyqYlRWIivr4mvCQ',
    appId: '1:801172071927:android:2aea5acb3e3981e0bdfaf2',
    messagingSenderId: '801172071927',
    projectId: 'dw-7-job-timer-1cb68',
    storageBucket: 'dw-7-job-timer-1cb68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ-TFjh4b7mh5tWDeI1C-YJ6etOYXFZBY',
    appId: '1:801172071927:ios:d530a1626ab30d06bdfaf2',
    messagingSenderId: '801172071927',
    projectId: 'dw-7-job-timer-1cb68',
    storageBucket: 'dw-7-job-timer-1cb68.appspot.com',
    iosClientId: '801172071927-31vi67g9vg5ls7q1jj01flppfibjpt7b.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobTimer',
  );
}
